# Generated by Django 3.2.22 on 2024-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
